quarkus.native.resources.includes=camel/route.camel.yaml
camel.main.routes-include-pattern=camel/route.camel.yaml

quarkus.datasource.jdbc=false
camel.vault.kubernetes.secrets=secret-basic-auth
camel.vault.kubernetes.refreshEnabled=true
camel.main.context-reload-enabled=true

# quarkus kubernetes client
quarkus.kubernetes-client.trust-certs=true
quarkus.kubernetes-client.namespace=default
# change the minikup ip
quarkus.kubernetes-client.api-server-url=https://192.168.39.23:8443
# minikube k config view --minify shows the correct paths of your minikube
quarkus.kubernetes-client.client-cert-file=/home/claudio/.minikube/profiles/minikube/client.crt
quarkus.kubernetes-client.client-key-file=/home/claudio/.minikube/profiles/minikube/client.key

# quarkus.log.category."org.postgresql".level=TRACE
# quarkus.log.category."org.postgresql".min-level=TRACE
# quarkus.log.category."org.apache.camel.component.jdbc".level=TRACE
# quarkus.log.category."org.apache.camel.component.jdbc".min-level=TRACE
quarkus.log.category."org.apache.camel.component.kubernetes".level=TRACE
quarkus.log.category."org.apache.camel.component.kubernetes".min-level=TRACE
quarkus.log.category."org.apache.camel.main".level=TRACE
quarkus.log.category."org.apache.camel.main".min-level=TRACE
# quarkus.log.category."io.fabric8.kubernetes.client.".level=TRACE
# quarkus.log.category."io.fabric8.kubernetes.client.".min-level=TRACE
# quarkus.log.category."org.springframework".level=TRACE
# quarkus.log.category."org.springframework".min-level=TRACE
# quarkus.log.category."io.quarkus.kubernetes.config".level=TRACE
# quarkus.log.category."io.quarkus.kubernetes.config".min-level=TRACE

# permission to watch the secret object
quarkus.kubernetes.rbac.roles.my-role.policy-rules.0.api-groups=
quarkus.kubernetes.rbac.roles.my-role.policy-rules.0.resources=secrets
quarkus.kubernetes.rbac.roles.my-role.policy-rules.0.verbs=get,watch,list
